# Generated by Django 5.1.4 on 2025-01-16 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0003_alter_women_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="women",
            name="is_published",
            field=models.BooleanField(
                choices=[(0, "Черновик"), (1, "Опубликовано")], default=True
            ),
        ),
        migrations.AddField(
            model_name="women",
            name="cat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="women.category",
            ),
        ),
    ]
