# Generated by Django 5.1.4 on 2025-01-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0007_husband_women_husbund"),
    ]

    operations = [
        migrations.RenameField(
            model_name="women",
            old_name="husbund",
            new_name="husband",
        ),
    ]
